
import java.awt.Color;

/*
 * To change this template, choose Tools | Templates * and open the template in the editor. */

/*
 * menuform.java
 *
 * Created on Aug 12, 2015, 8:55:36 AM
 */

/**
 *
 * @author Student
 */
public class lucky_color extends javax.swing.JFrame {
int num=person.talent_num;
    /** Creates new form menuform */
    public lucky_color() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.      * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblhead = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Lucky_Color = new javax.swing.JButton();
        About = new javax.swing.JButton();
        Life_Path = new javax.swing.JButton();
        Talent_Num = new javax.swing.JButton();
        Destiny_Num = new javax.swing.JButton();
        Personality_Num = new javax.swing.JButton();
        First_Phase = new javax.swing.JButton();
        Second_Phase = new javax.swing.JButton();
        Third_Phase = new javax.swing.JButton();
        Fourth_Phase = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setAutoscrolls(true);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setForeground(new java.awt.Color(153, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lucky-numerology1-logo.jpg"))); // NOI18N

        lblhead.setBackground(new java.awt.Color(255, 51, 0));
        lblhead.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        lblhead.setForeground(new java.awt.Color(255, 204, 0));
        lblhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhead.setText("Your Luck Colour Description ");
        lblhead.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblhead, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(871, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblhead, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));

        Lucky_Color.setFont(new java.awt.Font("Tahoma", 1, 11));
        Lucky_Color.setText("LUCKY COLOUR");
        Lucky_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lucky_ColorActionPerformed(evt);
            }
        });

        About.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        About.setText("ABOUT US");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });

        Life_Path.setFont(new java.awt.Font("Tahoma", 1, 11));
        Life_Path.setText("ULTIMATE NUMBER");
        Life_Path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Life_PathActionPerformed(evt);
            }
        });

        Talent_Num.setFont(new java.awt.Font("Tahoma", 1, 11));
        Talent_Num.setText("TALENT NUMBER");
        Talent_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Talent_NumActionPerformed(evt);
            }
        });

        Destiny_Num.setFont(new java.awt.Font("Tahoma", 1, 11));
        Destiny_Num.setText("DESTINY NUMBER");
        Destiny_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Destiny_NumActionPerformed(evt);
            }
        });

        Personality_Num.setFont(new java.awt.Font("Tahoma", 1, 11));
        Personality_Num.setText("PERSONALITY NUMBER");
        Personality_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personality_NumActionPerformed(evt);
            }
        });

        First_Phase.setFont(new java.awt.Font("Tahoma", 1, 11));
        First_Phase.setText("FIRST PHASE  0 TO 35");
        First_Phase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_PhaseActionPerformed(evt);
            }
        });

        Second_Phase.setFont(new java.awt.Font("Tahoma", 1, 11));
        Second_Phase.setText("SECOND PHASE  35 TO 44");
        Second_Phase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Second_PhaseActionPerformed(evt);
            }
        });

        Third_Phase.setFont(new java.awt.Font("Tahoma", 1, 11));
        Third_Phase.setText("THIRD PHASE  44 TO 53");
        Third_Phase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Third_PhaseActionPerformed(evt);
            }
        });

        Fourth_Phase.setFont(new java.awt.Font("Tahoma", 1, 11));
        Fourth_Phase.setText("FOURTH  PHASE  53 PLUS");
        Fourth_Phase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fourth_PhaseActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setText("HEART NUMBER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton3.setText("CHECK YOUR FATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(About, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(Life_Path, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(Talent_Num, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(Destiny_Num, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(Personality_Num, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(Lucky_Color, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(First_Phase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(Second_Phase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(Third_Phase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(Fourth_Phase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Life_Path, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Talent_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Destiny_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Personality_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lucky_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(First_Phase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Second_Phase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Third_Phase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fourth_Phase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        lblname.setFont(new java.awt.Font("Albertus", 1, 48));
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 51), 3, true));
        lblname.setOpaque(true);

        descarea.setColumns(20);
        descarea.setFont(new java.awt.Font("Albertus", 1, 18));
        descarea.setForeground(new java.awt.Color(153, 0, 0));
        descarea.setLineWrap(true);
        descarea.setRows(5);
        descarea.setWrapStyleWord(true);
        descarea.setAlignmentX(1.0F);
        descarea.setAlignmentY(1.0F);
        descarea.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(descarea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jScrollPane1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        this.setVisible(false);
        new aboutus().setVisible(true);
}//GEN-LAST:event_AboutActionPerformed
    
    private void Personality_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personality_NumActionPerformed
        this.setVisible(false);
        new pers_num1().setVisible(true);
}//GEN-LAST:event_Personality_NumActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
 
        String str_gold_1="People with the luck number 1 and the color yellow, are ambitious"+
                "and love to impress others.The majority of them are optimistic and generous. They like"+
                "to help and assist others. They have the joie de Vivre,cheerfulness and are"+
                "able to cope in most circumstances. Such people either love the yellow color,"+
                " or just hate it - but can never be indifferent to it.";
    String str_blue_2="These people love peace and tranquility around them. They have," +
               " relatively, small aspirations and are easy to satisfy. They have an" +
               " inner serenity and very high spiritual abilities. They are considered " +
               "somewhat selfish, because of their need to be alone occasionally. The blue" +
               "color may either be favorable or hated by them, but they can never be " +
               "indifferent to it.";
    String str_purple="People with this luck color have strong personalities." +
               "They possess mystical abilities and a very strong will power." +
               " These people are talented at convincing others about the rightness of their " +
               "actions in many different ways. They have a prominent personal magnetism and " +
               "create a secure and peaceful atmosphere around them. They are self confident," +
               " have a high self esteem and will do everything to gain the sympathy of others." +
               " Purple is their favorite color.";
    String str_red= "The number 4 people are very competitive."+
               "They have the ability to succeed and to advance themselves with no support.?" +
               " These people have a very dominant personality and are particularly romantic in nature.?" +
               " They are also ardent suitors. They are strong, " +
               "physically and mentally. The red color is their favorable or hated color," +
               " but they are never indifferent to it.";
    String str_orange="These people have a strong character, they are smart, sharp," +
               " and full of sense of humor. They are very communicative and are good " +
               "listener to others./" +
               " The number 5 people are very creative and will always find a brilliant solution to any problem. /" +
               "They are very good interlocutor to those who are under mental pressure and have the abilities to calm them. The orange color is their favorite or hated color, and they are always sensitive to it.";
    String str_green="Green people are conservative people that do not like extreme changes. /" +
               "They need to be secluded from others in order to contemplate their deep thoughts./" +
               " People with the green luck color may get confused or embarrassed very quickly /" +
               "and it is difficult to penetrate their privacy. Any change threatens their security; however, they will not show it. The green color is their favorite or hated color, and they are always sensitive to it.";
    String str_white="Number 7 people will constantly seek protection from the outside world. /" +
               "These people know how to hide their feelings and do not share their thoughts with others. /" +
               "These people prefer to be secluded most of the time and most of their personal c/" +
               "ontacts must be profitable to them in some way. They live in two worlds most of the time. The white color is their favorite or hated color, and they are always sensitive to it.";
    String str_lightblue="These people have built walls around themselves./" +
                       " Naturally it is difficult to create a close contact with them, /" +
                       "but those who will succeed, will find them as very good friends./" +
                       " The number 8 people are loyal to their friends and are always ready to help them, but they are not open for assistance and help from others. Their luck color can assist them a lot in their lives. They favor all shades of pale blue color.";
    String str_brown="No. 9 people are materialistic, they find security is in the earthly matters. /" +
                       "They have a tendency to be rebellious and need to prove their rightness./" +
                       " Their energy level is high, and have the ability to read" +
                       " other people precisely. Their sense of humor assists them in difficult times of suffering and low energy. They like the brown color very much.";
    
    switch(num)
    {
        case 1: lblhead.setText(" Lucky Color : Gold");
            lblname.setBackground(Color.YELLOW);
                lblname.setText("1");
                descarea.setText(str_gold_1);
                break;
        case 2: lblhead.setText(" Lucky Color : Blue");
                lblname.setBackground(Color.blue);
                lblname.setText("2");
                descarea.setText(str_blue_2);
                break;
        case 3: lblhead.setText(" Lucky Color : Purple");
            lblname.setBackground(Color.PINK);
                lblname.setText("3");
                descarea.append(" "+str_purple);
                break;
        case 4: lblhead.setText(" Lucky Color : Red");
            lblname.setBackground(Color.red);
                lblname.setText("4");
                descarea.setText(str_red);
                break;
        case 5: lblhead.setText(" Lucky Color : Orange");
            lblname.setBackground(Color.orange);
                lblname.setText("5");
                descarea.setText(str_orange);
                break;
        case 6: lblhead.setText(" Lucky Color : Green");
            lblname.setBackground(Color.green);
                lblname.setText("6");
                descarea.setText(str_green);
                break;
        case 7: lblhead.setText(" Lucky Color : White");
            lblname.setBackground(Color.white);
                lblname.setText("7");
                descarea.setText(str_white);
                break;
        case 8: lblhead.setText(" Lucky Color : Light Blue");
            lblname.setBackground(Color.black);
                lblname.setText("8");
                descarea.setText(str_lightblue);
                break;
        case 9: lblhead.setText(" Lucky Color : Brown");
            lblname.setBackground(Color.darkGray);
                lblname.setText("9");
                descarea.setText(str_brown);
                break;
       }

    }//GEN-LAST:event_formWindowActivated

    private void Life_PathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Life_PathActionPerformed
        this.setVisible(false);
        new ultimate_num1().setVisible(true);
    }//GEN-LAST:event_Life_PathActionPerformed

    private void Talent_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Talent_NumActionPerformed
       this.setVisible(false);
        new talent_num1().setVisible(true);
    }//GEN-LAST:event_Talent_NumActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.setVisible(false);
        new heart_num_1().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Destiny_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Destiny_NumActionPerformed
       this.setVisible(false);
        new destiny_num_1().setVisible(true);
    }//GEN-LAST:event_Destiny_NumActionPerformed

    private void Lucky_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lucky_ColorActionPerformed
        this.setVisible(false);
        new lucky_color().setVisible(true);
    }//GEN-LAST:event_Lucky_ColorActionPerformed

    private void First_PhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_PhaseActionPerformed
        this.setVisible(false);
        new path1_1().setVisible(true);
    }//GEN-LAST:event_First_PhaseActionPerformed

    private void Second_PhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Second_PhaseActionPerformed
        this.setVisible(false);
        new path2_1().setVisible(true);
    }//GEN-LAST:event_Second_PhaseActionPerformed

    private void Third_PhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Third_PhaseActionPerformed
        this.setVisible(false);
        new path3_1().setVisible(true);
    }//GEN-LAST:event_Third_PhaseActionPerformed

    private void Fourth_PhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fourth_PhaseActionPerformed
        this.setVisible(false);
        new path4_1().setVisible(true);
    }//GEN-LAST:event_Fourth_PhaseActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.setVisible(false);
        new mainpage().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About;
    private javax.swing.JButton Destiny_Num;
    private javax.swing.JButton First_Phase;
    private javax.swing.JButton Fourth_Phase;
    private javax.swing.JButton Life_Path;
    private javax.swing.JButton Lucky_Color;
    private javax.swing.JButton Personality_Num;
    private javax.swing.JButton Second_Phase;
    private javax.swing.JButton Talent_Num;
    private javax.swing.JButton Third_Phase;
    private javax.swing.JTextArea descarea;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblhead;
    private javax.swing.JLabel lblname;
    // End of variables declaration//GEN-END:variables

}
