
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;



/*
 * To change this template, choose Tools | Templates * and open the template in the editor. */

/*
 * menuform.java
 *
 * Created on Aug 12, 2015, 8:55:36 AM
 */

/**
 *
 * @author Student
 */
public class mainpage extends javax.swing.JFrame {

    /** Creates new form menuform */
    public mainpage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.      * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblhead = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        About = new javax.swing.JButton();
        Ultimate_num = new javax.swing.JButton();
        Talent_Num = new javax.swing.JButton();
        Heart_num = new javax.swing.JButton();
        Destiny_Num = new javax.swing.JButton();
        Personality_Num = new javax.swing.JButton();
        Lucky_Color = new javax.swing.JButton();
        First_Phase = new javax.swing.JButton();
        Second_Phase = new javax.swing.JButton();
        Third_Phase = new javax.swing.JButton();
        Fourth_Phase = new javax.swing.JButton();
        Main_page = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfyy = new javax.swing.JTextField();
        tfdd = new javax.swing.JComboBox();
        tfmm = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtultimate = new javax.swing.JTextField();
        txttalent = new javax.swing.JTextField();
        txtheart = new javax.swing.JTextField();
        txtdestiny = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setAutoscrolls(true);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setForeground(new java.awt.Color(153, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lucky-numerology1-logo.jpg"))); // NOI18N

        lblhead.setBackground(new java.awt.Color(255, 51, 0));
        lblhead.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        lblhead.setForeground(new java.awt.Color(255, 204, 0));
        lblhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhead.setText("Enter Your Personal Details");
        lblhead.setOpaque(true);
        lblhead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblheadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblhead, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(749, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblhead, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setEnabled(false);

        About.setFont(new java.awt.Font("Tahoma", 1, 11));
        About.setText("ABOUT US");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });

        Ultimate_num.setFont(new java.awt.Font("Tahoma", 1, 11));
        Ultimate_num.setText("ULTIMATE NUMBER");
        Ultimate_num.setEnabled(false);
        Ultimate_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ultimate_numActionPerformed(evt);
            }
        });

        Talent_Num.setFont(new java.awt.Font("Tahoma", 1, 11));
        Talent_Num.setText("TALENT NUMBER");
        Talent_Num.setEnabled(false);
        Talent_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Talent_NumActionPerformed(evt);
            }
        });

        Heart_num.setFont(new java.awt.Font("Tahoma", 1, 11));
        Heart_num.setText("HEART NUMBER");
        Heart_num.setEnabled(false);
        Heart_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Heart_numActionPerformed(evt);
            }
        });

        Destiny_Num.setFont(new java.awt.Font("Tahoma", 1, 11));
        Destiny_Num.setText("DESTINY NUMBER");
        Destiny_Num.setEnabled(false);
        Destiny_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Destiny_NumActionPerformed(evt);
            }
        });

        Personality_Num.setFont(new java.awt.Font("Tahoma", 1, 11));
        Personality_Num.setText("PERSONALITY NUMBER");
        Personality_Num.setEnabled(false);
        Personality_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personality_NumActionPerformed(evt);
            }
        });

        Lucky_Color.setFont(new java.awt.Font("Tahoma", 1, 11));
        Lucky_Color.setText("LUCKY COLOUR");
        Lucky_Color.setEnabled(false);
        Lucky_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lucky_ColorActionPerformed(evt);
            }
        });

        First_Phase.setFont(new java.awt.Font("Tahoma", 1, 11));
        First_Phase.setText("FIRST PHASE  0 TO 35");
        First_Phase.setEnabled(false);
        First_Phase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_PhaseActionPerformed(evt);
            }
        });

        Second_Phase.setFont(new java.awt.Font("Tahoma", 1, 11));
        Second_Phase.setText("SECOND PHASE  35 TO 44");
        Second_Phase.setEnabled(false);
        Second_Phase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Second_PhaseActionPerformed(evt);
            }
        });

        Third_Phase.setFont(new java.awt.Font("Tahoma", 1, 11));
        Third_Phase.setText("THIRD PHASE  44 TO 53");
        Third_Phase.setEnabled(false);
        Third_Phase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Third_PhaseActionPerformed(evt);
            }
        });

        Fourth_Phase.setFont(new java.awt.Font("Tahoma", 1, 11));
        Fourth_Phase.setText("FOURTH  PHASE  53 PLUS");
        Fourth_Phase.setEnabled(false);
        Fourth_Phase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fourth_PhaseActionPerformed(evt);
            }
        });

        Main_page.setFont(new java.awt.Font("Tahoma", 1, 11));
        Main_page.setText("CHECK YOUR FATE");
        Main_page.setEnabled(false);
        Main_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_pageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Third_Phase, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(Main_page, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(Second_Phase, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(First_Phase, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(Lucky_Color, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(Personality_Num, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(Destiny_Num, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(Talent_Num, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(Ultimate_num, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(About, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(Heart_num, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(Fourth_Phase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(21, 21, 21)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(About, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Ultimate_num, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Talent_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7)
                    .addComponent(Heart_num, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Destiny_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Personality_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Lucky_Color, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(First_Phase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Second_Phase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Third_Phase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Fourth_Phase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Main_page, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)))
        );

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 2, 24));
        jLabel1.setText("FIRST NAME");

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Birth Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24));
        jLabel3.setText("DAY");

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 2, 24));
        jLabel4.setText("MONTH");

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 2, 24));
        jLabel5.setText("YYYY");

        tfdd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        tfdd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tfddItemStateChanged(evt);
            }
        });

        tfmm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfdd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tfmm, 0, 75, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfyy, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(tfyy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 3, 36));
        jLabel8.setText("Your Number is: ");

        jButton11.setFont(new java.awt.Font("Monotype Corsiva", 3, 36));
        jButton11.setForeground(new java.awt.Color(51, 0, 255));
        jButton11.setText("PROCEED");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Albertus", 3, 18)); // NOI18N
        jButton1.setText("Check Fate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Albertus", 3, 18)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setText("ULTIMATE NUMBER:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("TALENT NUMBER:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setText("HEART NUMBER:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("DESTINY NUMBER:");

        txtultimate.setEditable(false);
        txtultimate.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtultimate.setForeground(new java.awt.Color(204, 0, 0));

        txttalent.setEditable(false);
        txttalent.setFont(new java.awt.Font("Tahoma", 1, 14));
        txttalent.setForeground(new java.awt.Color(204, 0, 0));

        txtheart.setEditable(false);
        txtheart.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtheart.setForeground(new java.awt.Color(204, 0, 0));

        txtdestiny.setEditable(false);
        txtdestiny.setFont(new java.awt.Font("Tahoma", 1, 14));
        txtdestiny.setForeground(new java.awt.Color(204, 0, 0));

        btndelete.setFont(new java.awt.Font("Albertus", 3, 18)); // NOI18N
        btndelete.setText("Delete");
        btndelete.setEnabled(false);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnsubmit.setFont(new java.awt.Font("Albertus", 3, 18)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.setEnabled(false);
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jLabel11.setText("Id no.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(45, 45, 45)
                                        .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel11)
                                        .addGap(56, 56, 56)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtdestiny, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel7))
                                                    .addComponent(jLabel9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtheart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                                    .addComponent(txttalent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                                    .addComponent(txtultimate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(132, 132, 132)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(btnsubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(btndelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(btnsearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addGap(615, 615, 615)
                                .addComponent(jButton11)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(txtultimate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(txttalent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(txtheart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(txtdestiny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jButton11)))
                        .addGap(79, 79, 79))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int sumdig(int n)
    {
        int s=0;
               while(n!=0)
               {
                   s+=(n%10);
                   n=n/10;
               }
        while (s>9)
            s=sumdig(s);
        return s;
    }
int calc_name_cons(String str)
{
        char ch;
        int l=str.length();
        int s=0,i=0;
        str=str.toUpperCase();
        for(i=0; i<l;i++)
        {
        switch(str.charAt(i))
        {
                 case 'J':
                 case 'S': s=s+1;break;
                 case 'B':
                 case 'k':
                 case 'T':s=s+2; break;
                 case 'C':
                 case 'L':s=s+3; break;
                 case 'D':
                 case 'M':
                 case 'V':s=s+4;break;
                 case 'N':
                 case 'W':s=s+5;break;
                 case 'F':
                 case 'X':s=s+6;break;
                 case 'G':
                 case 'P':
                 case 'Y':s=s+7;break;
                 case 'H':
                 case 'Q':
                 case 'Z':s=s+8;break;
                 case 'R':s=s+9;break;
        }
      }
      return s;
}
int calc_name(String str)
{
        char ch;
        int l=str.length();
        int s=0,i=0;
        str=str.toUpperCase();
        for(i=0; i<l;i++)
        {
        switch(str.charAt(i))
        {
                 case 'A':
                 case 'J':
                 case 'S': s=s+1;break;
                 case 'B':
                 case 'k':
                 case 'T':s=s+2; break;


                 case 'C':
                 case 'L':
                 case 'U':s=s+3; break;

                 case 'D':
                 case 'M':
                 case 'V':s=s+4;break;

                 case 'E':
                 case 'N':
                 case 'W':s=s+5;break;

                 case 'F':
                 case 'O':
                 case 'X':s=s+6;break;

                 case 'G':
                 case 'P':
                 case 'Y':s=s+7;break;


                 case 'H':
                 case 'Q':
                 case 'Z':s=s+8;break;

                 case 'I':
                 case 'R':s=s+9;break;
        }
      }
      return s;
}

int calc_name_vowels(String str)
{
        char ch;
        int l=str.length();
        int s=0,i=0;
        str=str.toUpperCase();
        for(i=0; i<l;i++)
        {
        switch(str.charAt(i))
        {
                 case 'A':s=s+1;break;
                 case 'U':s=s+3; break;
                 case 'E':s=s+5;break;
                 case 'O':s=s+6;break;
                 case 'I':s=s+9;break;
        }
      }
      return s;
}
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
Ultimate_num.setVisible(true);

        // TODO add your handling code here:
 
    }//GEN-LAST:event_formWindowActivated

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
    this.setVisible(false);
    new aboutus().setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_AboutActionPerformed

    private void Ultimate_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ultimate_numActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        new ultimate_num1().setVisible(true);
        
    }//GEN-LAST:event_Ultimate_numActionPerformed

    private void Talent_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Talent_NumActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new talent_num1 ().setVisible(true);
    }//GEN-LAST:event_Talent_NumActionPerformed

    private void Heart_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Heart_numActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new heart_num_1().setVisible(true);
    }//GEN-LAST:event_Heart_numActionPerformed

    private void Destiny_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Destiny_NumActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new destiny_num_1().setVisible(true);
    }//GEN-LAST:event_Destiny_NumActionPerformed

    private void Personality_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personality_NumActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
        new pers_num1().setVisible(true);
    }//GEN-LAST:event_Personality_NumActionPerformed

    private void Lucky_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lucky_ColorActionPerformed
    this.setVisible(true);
        new lucky_color().setVisible(true);
       
    }//GEN-LAST:event_Lucky_ColorActionPerformed

    private void First_PhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_First_PhaseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new path1_1().setVisible(true);
    }//GEN-LAST:event_First_PhaseActionPerformed

    private void Second_PhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Second_PhaseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new path2_1().setVisible(true);
    }//GEN-LAST:event_Second_PhaseActionPerformed

    private void Third_PhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Third_PhaseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new path3_1().setVisible(true);
    }//GEN-LAST:event_Third_PhaseActionPerformed

    private void Fourth_PhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fourth_PhaseActionPerformed
        // TODO add your handling code here
        this.setVisible(false);
       new path4_1().setVisible(true);
    }//GEN-LAST:event_Fourth_PhaseActionPerformed

    private void Main_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_pageActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new mainpage().setVisible(true);
    }//GEN-LAST:event_Main_pageActionPerformed

    private void tfddItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tfddItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tfddItemStateChanged

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:


        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/priyanka","root","password");
            Statement stmt = null;
            stmt = con.createStatement();
            String strSQL = "Insert into birthnum values("+(person.id)+",'"+(person.name)+"',"+(person.mm)+","+(person.yy)+","+(person.dd)+","+(person.talent_num)+","+(person.path1)+","+(person.path2)+","+(person.path3)+","+(person.path4)+","+(person.destiny_num)+","+(person.heart_num)+","+(person.person_num)+","+(person.ultimate_num)+");";
            stmt.executeUpdate(strSQL);
            JOptionPane.showMessageDialog(this,"Record Added");
            con.close();
            stmt.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }




}//GEN-LAST:event_btnsubmitActionPerformed

    private void lblheadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblheadMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_lblheadMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        person.id=Integer.parseInt(txtid.getText());
        person.dd= Integer.parseInt((String)tfdd.getSelectedItem());
        person.mm= Integer.parseInt((String)tfmm.getSelectedItem());
        person.yy= Integer.parseInt(tfyy.getText());
        int totd=sumdig(person.dd);
        int totm=sumdig(person.mm);
        int toty=sumdig(person.yy);
        int tot=totd+totm+toty;
        person.name = tfname.getText();
        person.talent_num = sumdig(tot); //Talent number + Lucky color
         //result.setText(""+fin); //TALENT NUMBER
        person.destiny_num=sumdig(calc_name(person.name)); //Destiny number Total of alphabets in name
        person.heart_num=sumdig(calc_name_vowels(person.name)); //Heart Number
        person.person_num=sumdig(calc_name_cons(person.name)); //Personality Number
        person.ultimate_num=sumdig(person.talent_num+person.destiny_num);
        //result.setText("Destiny Numbers"+name_num+"\nTalent Number "+fin+"\nHeart"+name_vowel_num+"\n Personality "+name_cons_num+"\nultimate"+ultimate_num1);
        person.path1=sumdig(totm+totd);
        person.path2=sumdig(totd+toty);
        person.path3=sumdig(person.path1+person.path2);
        person.path4=sumdig(totm+toty);
        //About.setEnabled(true);
        txtultimate.setText(" "+person.ultimate_num);
        txtdestiny.setText(" "+person.destiny_num);
        txttalent.setText(" "+person.talent_num);
        txtheart.setText(" "+person.heart_num);
        Ultimate_num.setEnabled(true);
        Talent_Num.setEnabled(true);
        Heart_num.setEnabled(true);
        Lucky_Color.setEnabled(true);
        Destiny_Num.setEnabled(true);
        Personality_Num.setEnabled(true);
        First_Phase.setEnabled(true);
        Second_Phase.setEnabled(true);
        Third_Phase.setEnabled(true);
        Fourth_Phase.setEnabled(true);
        Main_page.setEnabled(true);
        btnsearch.setEnabled(true);
        btnsubmit.setEnabled(true);
        btndelete.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
    int id = Integer.parseInt(txtid.getText());
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/priyanka","root","password");
            Statement stmt = null;
            ResultSet rs = null;
            stmt = con.createStatement();
            String strSQL ="select * from birthnum where id = "+id+";";
            rs=stmt.executeQuery(strSQL);
            if (rs.next())
            {
                person.dd=Integer.parseInt(rs.getString("dd"));
                person.mm=Integer.parseInt(rs.getString("mm"));
                person.yy=Integer.parseInt(rs.getString("yy"));
                person.name=rs.getString("name");
                person.destiny_num=Integer.parseInt(rs.getString("denisty_num"));
                person.heart_num=Integer.parseInt(rs.getString("heart_num"));
                person.talent_num=Integer.parseInt(rs.getString("talent_num"));
                person.ultimate_num=Integer.parseInt(rs.getString("ultimate_num"));
                person.path1=sumdig(sumdig(person.mm)+sumdig(person.dd));
                person.path2=sumdig(sumdig(person.dd)+sumdig(person.yy));
                person.path3=sumdig(person.path1+person.path2);
                person.path4=sumdig(sumdig(person.mm)+sumdig(person.yy));
                tfname.setText(rs.getString("name"));
                tfmm.setSelectedIndex(rs.getInt("mm")-1);
                tfdd.setSelectedIndex(rs.getInt("dd")-1);
                tfyy.setText(""+rs.getInt("yy"));
                txtultimate.setText(""+rs.getInt("ultimate_num"));
                txttalent.setText(""+rs.getInt("talent_num"));
                txtheart.setText(""+rs.getInt("heart_num"));
                txtdestiny.setText(""+rs.getInt("denisty_num"));
                Ultimate_num.setEnabled(true);
                Talent_Num.setEnabled(true);
                Heart_num.setEnabled(true);
                Lucky_Color.setEnabled(true);
                Destiny_Num.setEnabled(true);
                Personality_Num.setEnabled(true);
                First_Phase.setEnabled(true);
                Second_Phase.setEnabled(true);
                Third_Phase.setEnabled(true);
                Fourth_Phase.setEnabled(true);
                Main_page.setEnabled(true);
                btnsearch.setEnabled(true);
                btnsubmit.setEnabled(true);
                btndelete.setEnabled(true);
            }
            //stmt.executeUpdate(strSQL);

            con.close();
            stmt.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        btndelete.setEnabled(true);
        
        

}//GEN-LAST:event_btnsearchActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
int id = Integer.parseInt(txtid.getText());
              //delete
        try {
           Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/priyanka","root","password");
            Statement stmt = null;
            ResultSet rs = null;
            stmt = con.createStatement();
            String strSQL ="select * from birthnum where id = "+id+";";
            // Steps to confirm deletion
            int opt = JOptionPane.showConfirmDialog(null, "Are you sure to delete this record ?");
            if (opt == JOptionPane.YES_OPTION){
                try 
                {

                       strSQL = "Delete from birthnum where id = "+id+";";
                        int rowsEffected = stmt.executeUpdate(strSQL);
                        if (rowsEffected == 0)
                            JOptionPane.showMessageDialog(this, "Record does not exists");
                        else {
                            JOptionPane.showMessageDialog(this,"Record Deleted");
                        }
                    }

            catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Unable to delete");
                }
            }
            con.close();
            stmt.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
}//GEN-LAST:event_btndeleteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About;
    private javax.swing.JButton Destiny_Num;
    private javax.swing.JButton First_Phase;
    private javax.swing.JButton Fourth_Phase;
    private javax.swing.JButton Heart_num;
    private javax.swing.JButton Lucky_Color;
    private javax.swing.JButton Main_page;
    private javax.swing.JButton Personality_Num;
    private javax.swing.JButton Second_Phase;
    private javax.swing.JButton Talent_Num;
    private javax.swing.JButton Third_Phase;
    private javax.swing.JButton Ultimate_num;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblhead;
    private javax.swing.JComboBox tfdd;
    private javax.swing.JComboBox tfmm;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfyy;
    private javax.swing.JTextField txtdestiny;
    private javax.swing.JTextField txtheart;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txttalent;
    private javax.swing.JTextField txtultimate;
    // End of variables declaration//GEN-END:variables

}
